version: "3.6"
services:
  postgres:
    image: postgis/postgis:9.5-2.5-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: magus
    volumes:
      - magus_postgres_data:/var/lib/postgresql/data

volumes:
  magus_postgres_data:
